### ISSUE TITLE
Problème lorsque l'on veut écouter 2 fois le même film ou émission

### ISSUE THREAD

**Issue by jppilot** [dualB/plugin.video.telequebec#16]
Bonjour, depuis 2 jours, lorsque je veux écouter pour une deuxième fois un même film ou émission. Je reçois un message d'erreur.

 
2020-12-15 20:07:54.339 T:10392   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'simplejson.errors.JSONDecodeError'>
                                            Error Contents: Expecting value: line 1 column 1 (char 0)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.telequebec/default.py", line 73, in <module>
                                                navig.jouer_video(URL,SOURCE_ID)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.telequebec/resources/lib/navig.py", line 182, in jouer_video
                                                uri = getURI(video_json,refID)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.telequebec/resources/lib/navig.py", line 199, in getURI
                                                return m3u8BC(stream['sourceId'])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.telequebec/resources/lib/navig.py", line 206, in m3u8BC
                                                a= simplejson.loads(cache.get_cached_content('https://edge.api.brightcove.com/playback/v1/accounts/6150020952001/videos/%s?ad_config_id=%s' %(sourceId,config['ad']) ,True,[header]))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.simplejson/lib/simplejson/__init__.py", line 538, in loads
                                                return _default_decoder.decode(s)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.simplejson/lib/simplejson/decoder.py", line 370, in decode
                                                obj, end = self.raw_decode(s)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.simplejson/lib/simplejson/decoder.py", line 400, in raw_decode
                                                return self.scan_once(s, idx=_w(s, idx).end())
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.simplejson/lib/simplejson/scanner.py", line 79, in scan_once
                                                return _scan_once(string, idx)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.simplejson/lib/simplejson/scanner.py", line 39, in _scan_once
                                                raise JSONDecodeError(errmsg, string, idx)
                                            JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                            -->End of Python script error report<--

Ce seulement avec Telequebec

Merci !

**Comment by dualB** [comment]
Bonjour, peux-tu essayer d'abord de supprimer le cache de l'additiel (dans les options). Est-ce que le même comportement est observé de nouveau?

**Comment by jppilot** [comment]
Bonjour, j'ai essayé sans succès. 

Voici ce que j'ai essayé à date.
- effacer le cache de l'additiel
- effacer complètement Kodi et ré-installer tout
- connecter avec ou sans VPN
À chaque fois j'ai le même problème

**Comment by dualB** [comment]
Peux-tu me donner un exemple de contenu pour lequel tu observes ce comportement?

**Comment by jppilot** [comment]
Le film La guerre des tuques dans la section film/ciné-cadeau.

En fait pas mal toute les émissions/films une fois que tu les a écouté.

**Comment by jppilot** [comment]
J'ai aussi essayé de marquer le filn comme "non vue" sans succès

**Comment by TechnoPhysCAL** [comment]
Je n'arrive tout simplement pas à reproduire ce bogue. Puisque personne d'autres n'a soulevé le problème, ça semble donc être associé à votre installation spécifique.

**Comment by dualB** [comment]
Je n'arrive tout simplement pas à reproduire ce bogue. Puisque personne d'autres n'a soulevé le problème, ça semble donc être associé à votre installation spécifique.

**Comment by jppilot** [comment]
D'accord merci pour votre temps, étrangement je n'ai rien changé à mon setup et ce matin La guerre des tuques a fonctionné. Étrange...
