### ISSUE TITLE
cache.py: addon exits with an error when encountering accented character in the addon's path

### ISSUE THREAD

**Issue by Oxalin** [dualB/plugin.video.telequebec#2]
There is an error happening when the addon's path contains an accented character.

According to last night investigation, under cache.py, it seems ADDON_CACHE_BASEDIR is set with a problematic value when there is an accented character in the addon's path (in the user's home folder name to be exact). Because of this encoding / decoding error (mixing cp1252, unicode and utf-8 maybe), "if not os.path.exists(ADDON_CACHE_BASEDIR):" is resolved as true. Os.makedirs then tries to create the falsely missing folder where it will also fail output an error because the path contains a wrongly decoded accented character.

As a workaround, using '.decode("utf-8")' when setting ADDON_CACHE_BASEDIR fixes the value and everything else just falls in place as expected after that point.

Under Windows 10 64bit
with Kodi 16 - Jarvis
where the user's name (and thus the home folder path) contains an accented character

I'll attach the Kodi's logfile when I'll get home.

**Comment by Oxalin** [comment]
I haven't tested it, but the same problem may happen under clearcache.py and navig.py, I'll have to test further.

**Comment by Oxalin** [comment]
It seems related to this:
http://forum.kodi.tv/showthread.php?tid=124921&pid=1039311#pid1039311
and mostly this link: http://forum.kodi.tv/showthread.php?tid=125492

As explained here, http://mirrors.kodi.tv/docs/python-docs/13.0-gotham/xbmcaddon.html
getAddonInfo() returns a string and not unicode, thus needing proper decoding.

**Comment by Oxalin** [comment]
From kodi's logfile:
19:15:16 T:6724   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.WindowsError'>
                                            Error Contents: [Error 5] Acc鳠refus: 'C:\\Users\\Marie-Jos\xc3\xa9e Langlois\\AppData\\Roaming'
                                            Traceback (most recent call last):
                                              File "C:\Users\Marie-JosꥠLanglois\AppData\Roaming\Kodi\addons\plugin.video.telequebec-master\default.py", line 14, in <module>
                                                from resources.lib import content, parse, navig
                                              File "C:\Users\Marie-JosꥠLanglois\AppData\Roaming\Kodi\addons\plugin.video.telequebec-master\resources\lib\content.py", line 6, in <module>
                                                import urllib2, simplejson, parse, cache, re, xbmcaddon
                                              File "C:\Users\Marie-JosꥠLanglois\AppData\Roaming\Kodi\addons\plugin.video.telequebec-master\resources\lib\cache.py", line 17, in <module>
                                                os.makedirs(ADDON_CACHE_BASEDIR)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 150, in makedirs
                                                makedirs(head, mode)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\os.py", line 157, in makedirs
                                                mkdir(name, mode)
                                            WindowsError: [Error 5] Acc鳠refus: 'C:\\Users\\Marie-Jos\xc3\xa9e Langlois\\AppData\\Roaming'
                                            -->End of Python script error report<--
19:15:16 T:10892   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.telequebec/
19:15:16 T:10892   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.telequebec/) failed

**Comment by dualB** [comment]
C'est noté, je ferai la correction dans la prochaine version mineure.
