### ISSUE TITLE
Playback ne fonctionne plus depuis la nouvelle version

### ISSUE THREAD

**Issue by mbelang** [dualB/plugin.video.telequebec#8]
Sur Kodi 16

Voici l'output des logs:

```
21:15:19 3894204.750000 T:1550840736   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'split'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.telequebec/default.py", line 79, in <module>
                                                navig.jouer_video(URL,SOURCE_ID)
                                              File "/storage/.kodi/addons/plugin.video.telequebec/resources/lib/navig.py", line 159, in jouer_video
                                                uri = obtenirMeilleurStream(m3u8_pl)
                                              File "/storage/.kodi/addons/plugin.video.telequebec/resources/lib/navig.py", line 196, in obtenirMeilleurStream
                                                for line in pl.split('\n'):
                                            AttributeError: 'NoneType' object has no attribute 'split'
                                            -->End of Python script error report<--
21:15:19 3894205.000000 T:1963925504   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.telequebec/?url=http%3A%2F%2Fzonevideo.telequebec.tv%2Fmedia%2F41476&s
ourceId=e677ea63a4d44615b7507a7e66a3ec93]
```

**Comment by dualB** [comment]
Quelle version utilises-tu?

**Comment by dualB** [comment]
C'est bon, j'ai isolé le bug, ce sera corrigé.

**Comment by dualB** [comment]
Version 3.2.2 corrige le bug.
